### ISSUE TITLE
Sometime need give textbox the focus again to make change effect

### ISSUE THREAD

**Issue by TimLeaf** [noraesae/kawa#10]
I use your app on macOS Sierra.
I often change input sources between Chinese, Japanese, English,
but it doesn't always works very well when I use shortcuts.
Sometime need give textbox the focus again to make that change effect.
I need this so much, so I hope you can fix it!

**Comment by noraesae** [comment]
Hi there, thanks for your comment.

I guess the problem is caused by the known but in TIS. Ref: https://github.com/noraesae/kawa/issues/2

Apple keyboard layout has bug with complex input method such as CJK keyboard.  Can you check if the problem belongs to the bug?

**Comment by TimLeaf** [comment]
Thanks your reply.
I think it's same issue.
Quite an old bug, Apple isn't going to fix it...

**Comment by noraesae** [comment]
I'll try a workaround in #11.
