### ISSUE TITLE
Workaround for a known CJK layout bug

### ISSUE THREAD

**Issue by noraesae** [noraesae/kawa#11]
source: https://github.com/noraesae/kawa/issues/2#issuecomment-329489897

There's a known TIS bug about CJK, also written in README.

> There is a known bug in the TIS library of macOS that switching keyboard layouts doesn't work well when done programmingly, especially between complex input sources like CJK. Kawa once tried to resolve this problem using hacky workaround, which caused more bugs, did more bad than good. The option is removed in v0.1.3, and I decide to wait for the fix from macOS.

However, @zcbenz suggested a workaround, and I'd like to check if it works.

- If target is English
    - Select English
- If target is a language other than English
    - Switch to target language
    - Switch to English
    - Select previous language

ref:

- https://github.com/CodeFalling/fcitx-remote-for-osx/blob/7f7e2895d413df44f45ef5c9aa3d127e428a7cbc/fcitx-remote/main.m#L69
- https://github.com/tekezo/Karabiner/issues/308#issuecomment-190693550

**Comment by hilezi** [comment]
another workaround

try switch to spotlight or alfredapp if you're using alfredapp, and switch back.
