### ISSUE TITLE
Menu bar icon on a dark background

### ISSUE THREAD

**Issue by laughedelic** [noraesae/kawa#13]
I have a dark menu bar: 

<img width="459" alt="screen shot 2017-09-16 at 16 08 24" src="https://user-images.githubusercontent.com/766656/30512902-ae0e33ec-9af9-11e7-8981-15be5ddbc10a.png">

and the Kawa icon on it is basically invisible: <img width="30" alt="screen shot 2017-09-16 at 14 42 59" src="https://user-images.githubusercontent.com/766656/30512903-b4701f52-9af9-11e7-997c-842dfd52d6b9.png">

Not a problem for me personally, because I hid the icon anyway (after I setup convenient hotkeys in Kawa, I'm not going to open it again until I want to change them). I just wanted to notify you that there is this issue. Probably making some outline, inverting colors or the 3 bars non-transparent would help...

**Comment by laughedelic** [comment]
Here's a couple more screenshots for the context. With dark menu bar and light:
<img width="212" alt="screen shot 2017-09-16 at 16 17 56" src="https://user-images.githubusercontent.com/766656/30512953-dafe2870-9afa-11e7-8d73-e53e5ce72fb4.png">
<img width="208" alt="screen shot 2017-09-16 at 16 18 58" src="https://user-images.githubusercontent.com/766656/30512954-df31b39e-9afa-11e7-8fc4-f1b90baf95c7.png">

**Comment by noraesae** [comment]
Thanks for your report!

**Comment by noraesae** [comment]
Fixed and released as v1.0.1.

**Comment by laughedelic** [comment]
Just checked it. Looks good 👍

**Comment by noraesae** [comment]
@laughedelic 

FYI: macOS actually handles the color conversion in dark mode, so I had nothing to do but for setting `isTemplate` of the image to `true`.

**Comment by laughedelic** [comment]
I didn't know it. Nice then.
