### ISSUE TITLE
Couldn't set ctrl + ' as the shortcut key

### ISSUE THREAD

**Issue by thisiseast** [noraesae/kawa#14]
It wouldn't work when trying to make Ctrl + ' the shortcut, could you help with it please?
Thanks!

**Comment by thisiseast** [comment]
neither does Ctrl + , work

**Comment by noraesae** [comment]
I guess they are already used by other system shortcut? If one is already assigned, ir cannot be used.

Actually Kawa doesn't manage shortcuts, but [MASShortcut](https://github.com/shpakovski/MASShortcut) does handle it. If the shortcuts are not used already but cannot be used, please ask on the library's repo.
