### ISSUE TITLE
El Capitan and Swift 2 compatibility

### ISSUE THREAD

**Issue by noraesae** [noraesae/kawa#3]
I've struggled to make it work in Xcode 7 in El Capitan, but no good news. I succeeded to remove all build errors, but it doesn't work and crash right after running up.

I guess Apple changed their input source API, as it crashes on the following line without returning any result.

```swift
let arr = TISCreateInputSourceList(nil, false).takeUnretainedValue() as! [TISInputSource]
```

The previous code works with no problem in Yosemite.

In conclusion, it really stops me from looking any other issue further. If there is any suggestion or workaround, please feel free to leave a comment!

**Comment by deville** [comment]
What is the status of this issue? Code from both `master` and `el-capitan` branches builds just fine in Xcode 7.2.

**Comment by puttin** [comment]
these code workaround the problem for me:

```
let inputSourceList_nsarray = TISCreateInputSourceList(nil, false).takeRetainedValue() as NSArray
let inputSourceList = inputSourceList_nsarray as! [TISInputSource]
```

**Comment by jwmann** [comment]
Can confirm @puttin's workaround, Builds successfully. :+1:

**Comment by jwmann** [comment]
Seems to be getting an error on runtime though.
![screen shot 2016-03-04 at 17 54 07](https://cloud.githubusercontent.com/assets/436270/13542650/31e1312e-e232-11e5-8069-8c0860745fd4.png)

**Comment by noraesae** [comment]
I've just confirmed that it builds and works well with the PR #4 merged. Thank you guys!
