### ISSUE TITLE
[question] Is it possible to switch using only single ⌘ key press?

### ISSUE THREAD

**Issue by Alex-Just** [noraesae/kawa#5]
Hi! Wonderful app, thanks!

I used to switch input source (via Karabiner) to MyLang1 via LEFT ⌘ key single press and to MyLang2 via RIGHT ⌘ key single press, but unfortunately Karabiner no longer works with OSX Sierra.

Is it possible to add this feature to your app?

**Comment by noraesae** [comment]
Kawa uses [MASShortcut](https://github.com/shpakovski/MASShortcut) for shortcut management and it doesn't support registering shortcuts with only those meta keys. It seems Karabiner will support Sierra soon, so you may expect it to work in a while. Sorry that I cannot help much.

Thanks!
