### ISSUE TITLE
Ability to just cycle through input sources with one hotkey

### ISSUE THREAD

**Issue by mondaiguy** [noraesae/kawa#7]
I would like to be able to just cycle through two input sources, Japanese (Hiragana) and U.S., with just one hotkey.

OS X El Cap and macOS let you do this by just setting "Select next source in Input menu" and disabling "Select previous input source", but for some reason it doesn't work when I use my favorite key combo for this, which is ⌥Space. So that's why I need Kawa. But I don't want to set two different hotkeys, and that's the only thing Kawa lets me do.

**Comment by mondaiguy** [comment]
A bonus feature would be that an icon for the current input source flashes next to my cursor so I can immediately see what source I switched to, so I don't have to look up at the menu bar. That'd be awesome, really.

**Comment by mondaiguy** [comment]
I guess I could just get used to using a different hotkey for English and Hiragana.

**Comment by noraesae** [comment]
Cycling through input sources is provided by OS natively.
