### ISSUE TITLE
Inconsistent behavior when switching languages in Alfred & Spotlight

### ISSUE THREAD

**Issue by mondaiguy** [noraesae/kawa#8]
On macOS Sierra when you use Kawa, you can't seem to switch input sources when Spotlight or the launcher called Alfred are invoked. It will ignore the change until you leave the launcher and come back.

I contacted the Alfred folks about this and they thought that Alfred and Spotlight's standard mode of operation being a floating window was something Kawa didn't seem to be dealing with properly, but Alfred has a Compatibility Mode which changes Alfred from a floating window or non-activating panel to behaving like an app, taking focus when you show it.

What's weird is if I switch between the two input sources I have repeatedly, eventually it works. In both Alfred and Spotlight, although it took about 6 times before it worked in Spotlight.

I don't think this is an issue on OS X El Capitan, I couldn't reproduce on there this morning.

My settings in Kawa are:
U.S. : ⌥Space
Hiragana (Japanese) : ⌘Space

**Comment by noraesae** [comment]
Duplicated with #10. The input source API provided by Apple has a bug in CJK layouts.

**Comment by noraesae** [comment]
I'll try a workaround in #11.
